version: '3'

services:
  db_postgres:
    container_name: 'db_container'
    image: 'postgres:12.6-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/db:/var/lib/postgresql/data/

  express_app:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_postgres
    links:
      - db_postgres
